version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
