name: api-breakage
on:
  pull_request:
    branches: 
      - "*"

jobs:
  api-breakage:
    strategy:
      fail-fast: false
    container: swift:5.7-jammy
    runs-on: ubuntu-latest
    steps:
      - name: Check out package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    # https://github.com/actions/checkout/issues/766
      - name: Mark the workspace as safe
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Run API-breakage diagnosis
        run: swift package diagnose-api-breaking-changes origin/main
