name: Update LOC
on:
  push: { branches: [ main ] }

jobs:
  loc_post:
    runs-on: ubuntu-latest
    name: Post LOC
    steps:
      - name: Checkout out package
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install jq
      - name: Install tokei
        uses: giantswarm/install-binary-action@VERSION
        with:
          binary: "tokei"
          version: "12.1.2"
          download_url: "https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-unknown-linux-gnu.tar.gz"
          smoke_test: "${binary} --version"
      - name: Calculate LOC
        id: loc
        run: tokei -t swift -o json | jq .Swift.code
      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.loc.outputs }}";
          echo "Line Count: ${{ steps.loc.outputs }}";
      - name: "Post"
        uses: indiesdev/curl@v1
        with:
          url: https://rapi.mahdibm.com/v1/loc/DiscordBM
          method: "POST"
          accept: 200
          params: '{ "loc": "${{ steps.loc.outputs }}", "secret": "${{ secrets.GH_LOC_SECRET }}" }'
          timeout: 5000
